### ISSUE TITLE
Access denied when building blazor client

### ISSUE THREAD

**Issue by paulallington** [Daddoon/BlazorMobile#164] opened 2020-03-03 17:09 UTC
For the life of me I cannot work out why I'm getting this error when I build the Blazor App

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3191	Unable to create directory "obj\Debug\netstandard2.1\Razor\Pages\Account\". Access to the path 'obj\Debug\netstandard2.1\Razor\Pages\Account\' is denied.	MyProject.Client	C:\Program Files\dotnet\sdk\3.1.101\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.CodeGeneration.targets	146	

It's only when I include BlazorMobile.Build.

**Comment by paulallington** [comment] 2020-03-03 17:15
It's not always consistent - I'm now currently getting this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "dotnet "C:\Users\paul\.nuget\packages\blazormobile.build\3.2.0-preview1.20073.1\tools\netcoreapp3.0/BlazorMobile.Build.dll" auto-generate-native-bindings --input "C:\Users\paul\Git\MyProject\MyProject.Client\MyProject.Client.csproj" --intermediate-output-path "obj\Debug\netstandard2.1\"" exited with code 1.	MyProject.Client	C:\Users\paul\.nuget\packages\blazormobile.build\3.2.0-preview1.20073.1\tools\GenerateBlazorMobileBuild.targets	47	

and...

Severity	Code	Description	Project	File	Line	Suppression State
Error		Access to the path 'C:\Users\paul\Git\MyProject\MyProject.Client\obj\Debug\netstandard2.1\Razor' is denied.	BlazorBoilerplate.Client	C:\Users\paul\Git\MyProject\MyProject.Client\EXEC	1

**Comment by Daddoon** [comment] 2020-03-03 18:17
Hi ! I never had this error while using BlazorMobile.

Is it possible that you send me a repro project for testing ?

Did you start from scratch or from BlazorMobile template ?

Thanks !

Le mar. 3 mars 2020 à 18:15, Paul Allington <notifications@github.com> a
écrit :

**Comment by Daddoon** [comment] 2020-03-03 19:04
Also the BlazorMobile.Build package do not do anything about Razor pages generation. Did you tried restart Visual Studio ?

However the first error in your second post may be related to BlazorMobile, as I did had this error sometimes while working from source code. It seem that sometimes file are locked between projects generation. I may have to make some changes in bindings generation .

**Comment by paulallington** [comment] 2020-03-03 20:16
I used a BlazorMobile template, and then tried to apply it to my blazor project.  It works fine in the template solution, but even if I import the template projects in to my solution it comes up with all kinds of weird errors.  I'm happy for you to have a look if you'd be happy to?

**Comment by Daddoon** [comment] 2020-03-03 21:08
I will try to take a look in a few time. Still, do you have a repro project to attach here ?

Also can you give me:

- Your Visual Studio version
- The output of dotnet —info
- The output of dotnet —version 
- The version of Blazor you are using

**Comment by Daddoon** [comment] 2020-03-03 21:15
Also what are the « weird » error you were talking ? The one mentioned in this issue ? Thanks again

**Comment by Daddoon** [comment] 2020-03-04 12:43
In my opinion, there is maybe an issue with your machine the day you made your tests, or maybe a previous race condition locking some files. As it seem your project also have the Razor obj files locked, i don't think it's something related to BlazorMobile, as like i said before, the BlazorMobile.Build package don't do anything about Razor metadatas at build time.

However, i have made a little enchancement for the next version of the package that i will publish in a short future, as i have removed some code that was deleting directories recusrively at build time in the obj/BlazorMobileProxyClass folder.

I think this approach was maybe too aggressive (and maybe can cause some lock issue between build in some scenario ?) , and is not needed anymore, as the files generated at build time will be also cleaned automatically if needed without any external intervention, as they are referenced through the *.FileListAbsolute.txt file in the obj folder.

Just for the technical aspect, they are referenced for MSBuild through the current statement in the source code of the package, in **GenerateBlazorMobileBuild.targets**:

```xml
  <Target Name="AddGeneratedNativeProxyClass" DependsOnTargets="_AddGeneratedNativeProxyClass" BeforeTargets="CoreCompile">
    <ItemGroup>
      <Compile Include="$(IntermediateOutputPath)BlazorMobileProxyClass\**\*.cs" />
      <FileWrites Include="$(IntermediateOutputPath)BlazorMobileProxyClass\**\*.cs" />
    </ItemGroup>
  </Target>
```

So maybe you will have less issues in the next version if the errors are related to some Write/Delete conditions on the system.

If you still have issue, and want to preview the change mentionned, please install manually the attached **BlazorMobile.Build** Nuget package present in this zip file.

-- File removed --

Thanks !

**Comment by Daddoon** [comment] 2020-03-04 13:31
I may have found another possible issue causing this error !
Stay tuned !

**Comment by Daddoon** [comment] 2020-03-04 13:39
Internally,  the package do some research in your project in order to generate bindings for BlazorMobile, but exclude of course all generated code from bin and obj folders.

Ironically, the Microsoft **Directory.GetDirectories** seem to go into exceptions while doing myself the test to "exclude" the required folders...Because maybe it's locked because we were at build time and it is doing some cleanup.

But in fact we don't need to scan theses folders, and even if it would happen with an exception we should ignore them.

I guess i have to rewrite myself this part in order to workaround the Microsoft API behavior.

So you were right, i think your error about the Razor page locked is caused by the BlazorMobile.Build package, not because it's really used, but only because it's scanned and at the wrong time.

My full error just for info:

```xml
13>BlazorMobile.Build -> index.html to server_index.cshtml done in C:\2Bee\Sources\BlazorMobile\src\BlazorMobile.InteropBlazorApp
13>EXEC : error : Access to the path 'C:\2Bee\Sources\BlazorMobile\src\BlazorMobile.InteropBlazorApp\obj\Debug\netstandard2.1\BlazorMobileProxyClass\BlazorMobile.Common\Interfaces' is denied.
13>   at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 relativePath, String fullPath)
13>   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
13>   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
13>   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
13>   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
13>   at BlazorMobile.Build.Core.NativeBindingsHelper.GetAllCSharpFiles(String workingDir) in C:\2Bee\Sources\BlazorMobile\src\BlazorMobile.Build\Core\NativeBindingsHelper.cs:line 25
13>   at BlazorMobile.Build.Core.NativeBindingsHelper.GenerateNativeBindings(String projectFile, String intermediateOutputPath) in C:\2Bee\Sources\BlazorMobile\src\BlazorMobile.Build\Core\NativeBindingsHelper.cs:line 128
13>   at BlazorMobile.Build.Server.Commands.AutoGenerateNativeBindings.<>c__DisplayClass0_0.<Command>b__0() in C:\2Bee\Sources\BlazorMobile\src\BlazorMobile.Build\Cli\Commands\AutoGenerateNativeBindings.cs:line 31
```

Thanks for pointing the issue, it's always good to enhance the product.
This behavior seemed less visible in previous Visual Studio versions in my opinion, as i was not able to reproduce this often some times ago, but i may be wrong.

**Comment by paulallington** [comment] 2020-03-04 17:25
Interesting!  Well done that's amazing work.  I'm really looking forward to getting this working as it really changes a lot of possibilities for me here.  

I'll try out the build you sent and see how it gets on.  I've got another issue at the moment that I'm just trying to identify, but then I'll try this out

**Comment by Daddoon** [comment] 2020-03-04 17:31
Please be patient, i will send a fix for my previous message statement in a few minutes, that cover what i was talking about.

**Comment by Daddoon** [comment] 2020-03-04 18:19
Fix done, please take a look at this Nuget package:

[BlazorMobile.Build.3.2.1-preview1.20073.1.zip](https://github.com/Daddoon/BlazorMobile/files/4288969/BlazorMobile.Build.3.2.1-preview1.20073.1.zip)

When listed (by Visual Studio configuration, or by a Nuget.config file) and installed in your Blazor project, please restart Visual Studio.

Also if you already loaded a previous Nuget test build (from this issue) here with the same version, you have to delete it first from the Nuget cache located here: %userprofile%\.nuget\packages 

In my opinion this version should avoid your building issues now !

**Comment by Daddoon** [comment] 2020-03-04 19:36
For my own test, it's better but i'm still having some issue at another point sometime during build, some folders in obj seem to be locked without permission, like Visual Studio has taken some rights. Very weird, i'm wondering if it's not a bug.

I will take a look at this tomorrow too.

**Comment by Daddoon** [comment] 2020-03-04 19:43
Oops nevermind my last message, i have missed to update the reference BlazorMobile.Build package on my test project.

**Comment by paulallington** [comment] 2020-03-04 19:43
It seems to happen when there's another error during the build - for eg, I've got a problem with 

Microsoft.AspNetCore.Components.Authorization" Version="3.1.1"

So in the template project, I tested removing that to see what effect it has, which broke the build, and now the template project is getting the permission error as before (it wasn't before it had a build failure).  I restarted visual studio and it went back to building again.

**Comment by Daddoon** [comment] 2020-03-04 19:49
Did you have tested with the last NuGet package i posted here ?

**Comment by paulallington** [comment] 2020-03-04 19:59
Not in the template one actually, I'll try that.  I'm getting this error in the other project I tried it in:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unhandled exception. Mono.Linker.Steps.XmlResolutionException: Failed to process XML description: <unspecified>	MyProject.Client	C:\Users\paul\.nuget\packages\microsoft.aspnetcore.blazor.build\3.2.0-preview1.20073.1\targets\Blazor.MonoRuntime.targets	258

**Comment by Daddoon** [comment] 2020-03-04 20:53
It does not seem to be BlazorMobile related for the last error.

But just for a clean test:

- Update any Blazor WASM project with the last Nuget I send.
- If you just added this to a non-template blazor project, check that the generated server_index.cshtml file BuildActions property is set to **None**.
- Close Visual Studio completely 
- Delete old Nuget packages from cache
- Delete obj and bin folders from all projects of your solution 
- Then restart Visual Studio 2019
- Rebuild the solution

**Comment by paulallington** [comment] 2020-03-05 08:40
The project is building, I'm not getting a zip file out, but everything is building so that nuget package you sent appears to have sorted that issue

**Comment by Daddoon** [comment] 2020-03-05 08:48
Are you sure you properly installed the package on your Blazor project ?
Check your Visual Studio console logs. You should see something like this:

```bash
BlazorMobile Build result -> App package present in C:\2Bee\Sources\BlazorMobile\src\BlazorMobile.InteropBlazorApp\bin\BlazorMobile.InteropBlazorApp.zip.
```

...if the Nuget package is properly installed on your project, and the MSBuild event running.

**Comment by paulallington** [comment] 2020-03-05 08:55
Omg, the package had disappeared from the solution.  Re-added and zip file created.  Well done :)

**Comment by Daddoon** [comment] 2020-03-05 08:57
Cool ! Tell me if build failure continue to occur then !

I will try to ship today or tomorrow a big update for BlazorMobile, that also include this current fix, so you will be able to update your project from the official Nuget repository instead !

**Comment by paulallington** [comment] 2020-03-05 08:58
Brill thanks!  It's a brilliant package, I'm really looking forward to making the most from it

**Comment by Daddoon** [comment] 2020-03-05 09:05
Thanks a lot !

Thanks for using it, as this project is not advertised by anyone (not even myself at the moment), and the Microsoft press may hide this a little bit, as their new experimental project is called Mobile Blazor Bindings !

However their goal are not the same as they are focusing about using the Blazor programming style for Native mobiles apps, not about shipping an Hybrid web apps model as this project.

**Comment by Daddoon** [comment] 2020-03-06 13:15
Closing this issue. Update will be shipped today or tomorrow.

**Closed as completed by Daddoon** 2020-03-06 13:15 UTC
Labels: bug
