### ISSUE TITLE
dot new blazormobile creates Common project which causes cyclic issue with restore

### ISSUE THREAD

**Issue by 4deeptech** [Daddoon/BlazorMobile#105] opened 2019-09-09 17:01 UTC
The getting started says to issue a

```dotnet new blazormobile```

This creates a project called blazormobile.Common which references a package called blazormobile.Common and throws a cyclic dependency error upon restore.

I tried passing the -n param to give the created solution/project a different name and it seemed to clear up the issue.

**Comment by Daddoon** [comment] 2019-09-09 17:10
I was able to reproduce this issue if naming the source folder to create "BlazorMobile". You are right, creating and using the same namespace as the NuGet package do something wrong.

Thanks for your report!

**Comment by Daddoon** [comment] 2019-09-09 22:12
Also by default the dotnet new command create a project name according to the current folder. Are you sure your folder was not named BlazorMobile ? 

I will see to update the doc with -n parameter, i will check the Microsoft documentation.

**Comment by Daddoon** [comment] 2019-09-10 08:31
Again, thanks for the report @4deeptech .

I updated the doc according to your feedback [here](https://github.com/Daddoon/BlazorMobile/blob/master/README.md#cyclic-restore-issue-at-project-template-creation) and [here](https://github.com/Daddoon/BlazorMobile/blob/master/README.md#getting-started-from-sample)

As in my opinion this case is not very critical, and because it's now documented, i will close this issue.

Greetings!

**Closed as completed by Daddoon** 2019-09-10 08:31 UTC
Labels: bug

**Comment by 4deeptech** [comment] 2019-09-10 13:42
@Daddoon You are correct, I did indeed have the command prompt in a folder by the same name. thanks for updating the docs.  Since it was a quick test to see how it all works I just created a folder by that name and tried it out there. Haven't run into the cyclic issue before and never crossed my mind.  Coincidence actually since the template creates a "Common" project AND there is a nuget package of the same name. Either way, thanks for updating the docs!

**Comment by Daddoon** [comment] 2019-09-10 14:51
Thanks for your feedback !

Actually, i never crossed my mind too about the shared interface project called "Common" with a specific case like this one.

Somehow, i think it was not a good Design idea of my side for the project name, i think **BlazorMobile.Common** is a good name for a NuGet package, but i think it would have been more clear if i had called the *.Common project *.Shared instead, like official Blazor templates.

I will rename the Common project template to Shared in a future release. I will update the migration part and hint about this template change if people want to also update their assemblies name according to the new structure.
