### ISSUE TITLE
The type initializer for 'Unosquare.Swan.Runtime' threw an exception.

### ISSUE THREAD

**Issue by paulallington** [Daddoon/BlazorMobile#176] opened 2020-03-14 21:57 UTC
I'm getting this error when the app is deployed to an emulator.  Any idea what it might be?

500 - Internal Server Error
Message

Failing module name: Web API Module
The type initializer for 'Unosquare.Swan.Runtime' threw an exception.
Object reference not set to an instance of an object.

Stack Trace

  at Unosquare.Swan.Formatters.Json+<>c.b__26_1 (System.Reflection.PropertyInfo x) [0x00000] in <341fab0ea132420086b2c4d8cba02db5>:0 
  at System.Linq.Enumerable+WhereSelectArrayIterator`2[TSource,TResult].MoveNext () [0x0002c] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/System.Linq/src/System/Linq/Where.cs:464 
  at System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].MoveNext () [0x0004e] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/System.Linq/src/System/Linq/Where.cs:140 
  at System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00015] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/System.Linq/src/System/Linq/AnyAll.cs:20 
  at Unosquare.Swan.Formatters.Json.GetExcludedNames (System.Type type, System.String[] excludedNames) [0x0003c] in <341fab0ea132420086b2c4d8cba02db5>:0 
  at Unosquare.Swan.Formatters.Json.Serialize (System.Object obj, System.Boolean format, System.String typeSpecifier, System.Boolean includeNonPublic, System.String[] includedNames, System.String[] excludedNames, System.Collections.Generic.List`1[T] parentReferences) [0x00034] in <341fab0ea132420086b2c4d8cba02db5>:0 
  at Unosquare.Swan.Formatters.Json.Serialize (System.Object obj, System.Boolean format, System.String typeSpecifier, System.Boolean includeNonPublic, System.String[] includedNames, System.String[] excludedNames) [0x00000] in <341fab0ea132420086b2c4d8cba02db5>:0 
  at Unosquare.Labs.EmbedIO.Extensions.JsonResponseAsync (Unosquare.Labs.EmbedIO.IHttpContext context, System.Object data, System.Threading.CancellationToken cancellationToken, System.Boolean useGzip) [0x00000] in <326850a19f504e73803cfb6b39c0a49f>:0 
  at Unosquare.Labs.EmbedIO.Extensions.JsonResponse (Unosquare.Labs.EmbedIO.IHttpContext context, System.Object data) [0x00000] in <326850a19f504e73803cfb6b39c0a49f>:0 
  at Unosquare.Labs.EmbedIO.Extensions.JsonExceptionResponse (Unosquare.Labs.EmbedIO.IHttpContext context, System.Exception ex, System.Net.HttpStatusCode statusCode) [0x0000c] in <326850a19f504e73803cfb6b39c0a49f>:0 
  at BlazorMobile.Controller.BlazorController.BlazorAppRessources () [0x001a6] in C:\2Bee\Sources\BlazorMobile\src\BlazorMobile\Controller\BlazorController.cs:132 
  at Unosquare.Labs.EmbedIO.Modules.WebApiModule.<.ctor>b__2_0 (Unosquare.Labs.EmbedIO.IHttpContext context, System.Threading.CancellationToken ct) [0x00226] in <326850a19f504e73803cfb6b39c0a49f>:0 
  at Unosquare.Swan.Formatters.Json+<>c.b__26_1 (System.Reflection.PropertyInfo x) [0x00000] in <341fab0ea132420086b2c4d8cba02db5>:0 
  at System.Linq.Enumerable+WhereSelectArrayIterator`2[TSource,TResult].MoveNext () [0x0002c] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/System.Linq/src/System/Linq/Where.cs:464 
  at System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].MoveNext () [0x0004e] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/System.Linq/src/System/Linq/Where.cs:140 
  at System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00015] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corefx/src/System.Linq/src/System/Linq/AnyAll.cs:20 
  at Unosquare.Swan.Formatters.Json.GetExcludedNames (System.Type type, System.String[] excludedNames) [0x0003c] in <341fab0ea132420086b2c4d8cba02db5>:0 
  at Unosquare.Swan.Formatters.Json.Serialize (System.Object obj, System.Boolean format, System.String typeSpecifier, System.Boolean includeNonPublic, System.String[] includedNames, System.String[] excludedNames, System.Collections.Generic.List`1[T] parentReferences) [0x00034] in <341fab0ea132420086b2c4d8cba02db5>:0 
  at Unosquare.Swan.Formatters.Json.Serialize (System.Object obj, System.Boolean format, System.String typeSpecifier, System.Boolean includeNonPublic, System.String[] includedNames, System.String[] excludedNames) [0x00000] in <341fab0ea132420086b2c4d8cba02db5>:0 
  at Unosquare.Labs.EmbedIO.Extensions.JsonResponseAsync (Unosquare.Labs.EmbedIO.IHttpContext context, System.Object data, System.Threading.CancellationToken cancellationToken, System.Boolean useGzip) [0x00000] in <326850a19f504e73803cfb6b39c0a49f>:0 
  at Unosquare.Labs.EmbedIO.Extensions.JsonResponse (Unosquare.Labs.EmbedIO.IHttpContext context, System.Object data) [0x00000] in <326850a19f504e73803cfb6b39c0a49f>:0 
  at Unosquare.Labs.EmbedIO.Extensions.JsonExceptionResponse (Unosquare.Labs.EmbedIO.IHttpContext context, System.Exception ex, System.Net.HttpStatusCode statusCode) [0x0000c] in <326850a19f504e73803cfb6b39c0a49f>:0 
  at BlazorMobile.Controller.BlazorController.BlazorAppRessources () [0x001a6] in C:\2Bee\Sources\BlazorMobile\src\BlazorMobile\Controller\BlazorController.cs:132 
  at Unosquare.Labs.EmbedIO.Modules.WebApiModule.<.ctor>b__2_0 (Unosquare.Labs.EmbedIO.IHttpContext context, System.Threading.CancellationToken ct) [0x00226] in <326850a19f504e73803cfb6b39c0a49f>:0 
  at Unosquare.Labs.EmbedIO.HttpHandler.ProcessRequest (System.Threading.CancellationToken ct) [0x00144] in <326850a19f504e73803cfb6b39c0a49f>:0

**Comment by Daddoon** [comment] 2020-03-15 00:11
I never had this error before.

- Did you have this error starting from template ?
- Are you using EmbedIO NuGet package in your project ?
- Which version of Blazor are you using ? BlazorMobile is not yet compatible with the latest version released the 9 March 2020 (the 3.2.0-preview2-x)
- Is your emulator x86 or ARM ? Did you try with a real device instead ?
- Are you generating an AAB or an APK file ? AAB is not yet supported (mainly related on how GeckView engine is working but I doubt your error is related to that).
- Generally speaking you must keep the same EmbedIO version targeted in BlazorMobile reference, if you use it by yourself.

**Comment by Daddoon** [comment] 2020-03-15 00:29
Seems to occurring during a BlazorMobile ressource request in the EmbedIO webserver.

How are you loading your App package ? Are you using some BlazorMobile API ?

When is this error occurring ? Do you have it on iOS or UWP ?

Can you send a minimal repro project ?

**Comment by paulallington** [comment] 2020-03-15 16:46
Did you have this error starting from template ?
- no, it loads fine from the template

Are you using EmbedIO NuGet package in your project ?
- no (at least not that I'm aware of)

Which version of Blazor are you using ? BlazorMobile is not yet compatible with the latest version released the 9 March 2020 (the 3.2.0-preview2-x)
- tried with pre 9th March, and the latest version

Is your emulator x86 or ARM ? Did you try with a real device instead ?
- x86, and same error on a real device

Are you generating an AAB or an APK file ? AAB is not yet supported (mainly related on how GeckView engine is working but I doubt your error is related to that).
- APK

Generally speaking you must keep the same EmbedIO version targeted in BlazorMobile reference, if you use it by yourself.
- It's not used in my app

How are you loading your App package ? Are you using some BlazorMobile API ?
- I've essentially tried to just copy the template in to my app

When is this error occurring ? Do you have it on iOS or UWP ?
- Android is this error - I've not got it working on iOS yet

Can you send a minimal repro project ?
Yes.  Downloadable here: https://cp.sync.com/dl/6fb4b0b40/m4ndg4i8-mkymb6xn-szwsjs4t-sk7thi54
(I've stripped it down to the minimum, but with references etc in place).

**Comment by Daddoon** [comment] 2020-03-15 17:48
- Beware, you are using some external references loaded from a CDN in your app (fontawesome, tinymce), consider having an offline version embedded in your app. If your device cannot reach internet for any reason, how will it load theses ressources ?
- I may be more explicit in the doc (or changing the default template), but you may have to change your **OnBlazorWebViewNavigationHandler** in order to allow some required external call (like your remote API), and also tell the device that you don't want to do anything, as "external ressources" called are opened in an external browser by default in the template. See:

```csharp
using BlazorMobile.Common;
using BlazorMobile.Services;
using System;
using System.Collections.Generic;
using System.Net;
using System.Text;
using Xamarin.Forms;

namespace Doddle.App.Handler
{
    public static class OnBlazorWebViewNavigationHandler
    {
        public static void OnBlazorWebViewNavigating(object sender, WebNavigatingEventArgs e)
        {
            var applicationBaseURL = WebApplicationFactory.GetBaseURL() + "/";

            if (e.Url.Equals(applicationBaseURL, StringComparison.OrdinalIgnoreCase))
            {
                //This is our application base URI. We should do nothing and continue navigating to the app
                e.Cancel = false;
            }
            else if (e.Url.StartsWith(WebApplicationFactory.GetBaseURL(), StringComparison.OrdinalIgnoreCase))
            {
                //Here, our application is loading an URI
                //You may add a custom logic, like opening a new view, changing the URI parameters then opening a view...

                e.Cancel = true;

                switch (BlazorDevice.RuntimePlatform)
                {
                    default:
                        Device.OpenUri(new Uri(WebUtility.UrlDecode(e.Url)));
                        break;
                }
            }
            else
            {
                //If here this is not our application loading an URI
                //You may add a custom logic, like opening a new view, changing the URI parameters then opening a view...

                e.Cancel = true;

                switch (BlazorDevice.RuntimePlatform)
                {
                    default:
                        Device.OpenUri(new Uri(WebUtility.UrlDecode(e.Url)));
                        break;
                }
            }
        }
    }
}
```

May become:

```csharp
using BlazorMobile.Common;
using BlazorMobile.Services;
using System;
using System.Collections.Generic;
using System.Net;
using System.Text;
using Xamarin.Forms;

namespace Doddle.App.Handler
{
    public static class OnBlazorWebViewNavigationHandler
    {
        public static void OnBlazorWebViewNavigating(object sender, WebNavigatingEventArgs e)
        {
            var applicationBaseURL = WebApplicationFactory.GetBaseURL() + "/";

            if (e.Url.Equals(applicationBaseURL, StringComparison.OrdinalIgnoreCase))
            {
                //This is our application base URI. We should do nothing and continue navigating to the app
                e.Cancel = false;
            }
            else if (e.Url.StartsWith(WebApplicationFactory.GetBaseURL(), StringComparison.OrdinalIgnoreCase))
            {
                //Here, our application is loading an URI
                //You may add a custom logic, like opening a new view, changing the URI parameters then opening a view...

                e.Cancel = true;

                switch (BlazorDevice.RuntimePlatform)
                {
                    default:
                        Device.OpenUri(new Uri(WebUtility.UrlDecode(e.Url)));
                        break;
                }
            }
            else
            {
                //If here this is not our application loading an URI
                //You may add a custom logic, like opening a new view, changing the URI parameters then opening a view...

                e.Cancel = false;

                switch (BlazorDevice.RuntimePlatform)
                {
                    default:
                        //Device.OpenUri(new Uri(WebUtility.UrlDecode(e.Url)));
                        break;
                }
            }
        }
    }
}
```

Instead (See the last part). You may also do your own rule in your code, site-by-bsite. See [Validating the Blazor application navigation](https://github.com/Daddoon/BlazorMobile#validating-the-blazor-application-navigation) for more information about this.

- I have added Remote debug connection on your Native project and Blazor (active only in debuug mode). Please modify **BlazorMobileService.EnableClientToDeviceRemoteDebugging** in your Blazor app in order to match the IP address of your device / emulator. You can then Deploy on the emulator, launch the app (let it stay opened) and then you can try to open your Web app from a regular browser on your PC, this will allow the external web app to be connected as it would be on the embedded app. See [Device remote debugging & Debugging from NET Core 3.0](https://github.com/Daddoon/BlazorMobile#device-remote-debugging--debugging-from-net-core-30) for more info.

Even if you don't do it on the *.Server project (as stated in the doc), it works on the regular WebAssembly project (you are just missing the .NET Core debugging stuff). In my opinion you have a Cross-origin problem with your external API.

There is what i got in my browser console:

>Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://doddle.app/api/Account/GetUser. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.
>
> WASM: ﻿Unhandled exception rendering component: blazor.webassembly.js:1:34702
> WASM: WebAssembly.JSException: TypeError: NetworkError when attempting to fetch resource. blazor.webassembly.js:1:34702
> WASM:   at WebAssembly.Net.Http.HttpClient.WasmHttpMessageHandler.doFetch (System.Threading.Tasks.TaskCompletionSource`1[TResult] tcs, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) <0x2526198 + 0x00988> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at WebAssembly.Net.Http.HttpClient.WasmHttpMessageHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) <0x24f8770 + 0x00184> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at Toolbelt.Blazor.HttpClientInterceptor.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) <0x24fe028 + 0x00148> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) <0x252ab10 + 0x00124> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at System.Net.Http.HttpClient.GetStringAsyncCore (System.Threading.Tasks.Task`1[TResult] getTask) <0x253d2a8 + 0x000e4> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at Microsoft.AspNetCore.Components.HttpClientJsonExtensions.GetJsonAsync[T] (System.Net.Http.HttpClient httpClient, System.String requestUri) <0x24d2d58 + 0x000c8> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at Doddle.Client.Services.Implementations.AuthorizeApi.GetUser () <0x249e1e8 + 0x0010e> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at Doddle.Client.States.IdentityAuthenticationStateProvider.GetUserInfo () <0x249d578 + 0x000e4> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at Doddle.Client.States.IdentityAuthenticationStateProvider.GetAuthenticationStateAsync () <0x24a0c50 + 0x000ec> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync () <0x2597d68 + 0x00126> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion (System.Threading.Tasks.Task task) <0x25987e8 + 0x000e6> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x23ad7e0 + 0x001fc> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x25992d0 + 0x000c2> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM: ﻿Detected Blazor implementation: WebAssembly (Client-side) blazor.webassembly.js:1:34654
> BlazorMobile: trying to open a new connection line 1 > scriptElement:32:25
> BlazorMobile: Connecting to websocket server: ws://192.168.0.148:8888/contextBridge line 1 > scriptElement:59:21
> Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://doddle.app/api/Account/GetUser. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.
> 
> WASM: Unhandled exception rendering component: blazor.webassembly.js:1:34702
> WASM: WebAssembly.JSException: TypeError: NetworkError when attempting to fetch resource. blazor.webassembly.js:1:34702
> WASM:   at WebAssembly.Net.Http.HttpClient.WasmHttpMessageHandler.doFetch (System.Threading.Tasks.TaskCompletionSource`1[TResult] tcs, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) <0x2526198 + 0x00988> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at WebAssembly.Net.Http.HttpClient.WasmHttpMessageHandler.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) <0x24f8770 + 0x00184> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at Toolbelt.Blazor.HttpClientInterceptor.SendAsync (System.Net.Http.HttpRequestMessage request, System.Threading.CancellationToken cancellationToken) <0x24fe028 + 0x00148> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered (System.Threading.Tasks.Task`1[TResult] sendTask, System.Net.Http.HttpRequestMessage request, System.Threading.CancellationTokenSource cts, System.Boolean disposeCts) <0x252ab10 + 0x00124> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at System.Net.Http.HttpClient.GetStringAsyncCore (System.Threading.Tasks.Task`1[TResult] getTask) <0x253d2a8 + 0x000e4> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at Microsoft.AspNetCore.Components.HttpClientJsonExtensions.GetJsonAsync[T] (System.Net.Http.HttpClient httpClient, System.String requestUri) <0x24d2d58 + 0x000c8> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at Doddle.Client.Services.Implementations.AuthorizeApi.GetUser () <0x249e1e8 + 0x0010e> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at Doddle.Client.States.IdentityAuthenticationStateProvider.GetUserInfo () <0x249d578 + 0x000e4> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at Doddle.Client.States.IdentityAuthenticationStateProvider.GetAuthenticationStateAsync () <0x24a0c50 + 0x000ec> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync () <0x2597d68 + 0x00126> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion (System.Threading.Tasks.Task task) <0x25987e8 + 0x000e6> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x23ad7e0 + 0x001fc> in <filename unknown>:0 blazor.webassembly.js:1:34702
> WASM:   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x25992d0 + 0x000c2> in <filename unknown>:0 blazor.webassembly.js:1:34702
> BlazorMobile: Connected to websocket server line 1 > scriptElement:63:29
> WASM: Initialization success: True blazor.webassembly.js:1:34654
> WASM: Device is: Android

- However sorry i'm not able to reproduce your EmbedIO exception at all ! What is your Android version ? What is your OS ? What is your Visual Studio version ? Can you try to delete all your "obj" folders from your working solution folder and try again ?

**Comment by Daddoon** [comment] 2020-03-15 17:51
Find attached you modified repro project:

[Doddle_20200315.zip](https://github.com/Daddoon/BlazorMobile/files/4334701/Doddle_20200315.zip)

**Comment by Daddoon** [comment] 2020-03-19 11:11
I close this issue.
If you still have the error, please inform here.

**Closed as completed by Daddoon** 2020-03-19 11:11 UTC
